[UPSTREAM]
    name forward-balancing

[NODE]
    name node1
    host 127.0.0.1
    port 7777

[NODE]
    name node2
    host 127.0.0.1
    port 7777

[NODE]
    name node3
    host 127.0.0.1
    port 7777

[NODE]
    name node4
    host 127.0.0.1
    port 7777
[NODE]
    name node5
    host 127.0.0.1
    port 7777

[NODE]
    name node6
    host 127.0.0.1
    port 7777

[NODE]
    name node7
    host 127.0.0.1
    port 7777

[NODE]
    name node8
    host 127.0.0.1
    port 7777
[NODE]
    name node9
    host 127.0.0.1
    port 7777

[NODE]
    name node10
    host 127.0.0.1
    port 7777
[NODE]
    name node11
    host 127.0.0.1
    port 7777

[NODE]
    name node12
    host 127.0.0.1
    port 7777
[NODE]
    name node13
    host 127.0.0.1
    port 7777

[NODE]
    name node14
    host 127.0.0.1
    port 7777

[NODE]
    name node15
    host 127.0.0.1
    port 7777

[NODE]
    name node16
    host 127.0.0.1
    port 7777
[NODE]
    name node17
    host 127.0.0.1
    port 7777

[NODE]
    name node18
    host 127.0.0.1
    port 7777

[NODE]
    name node19
    host 127.0.0.1
    port 7777

[NODE]
    name node20
    host 127.0.0.1
    port 7777
[NODE]
    name node21
    host 127.0.0.1
    port 7777

[NODE]
    name node22
    host 127.0.0.1
    port 7777
[NODE]
    name node23
    host 127.0.0.1
    port 7777

[NODE]
    name node24
    host 127.0.0.1
    port 7777
