[SERVICE]
    Flush        0.000001
    Log_Level    info

[INPUT]
    Name         dummy
    Rate         5000000
    Tag          bench_tag
    Threaded     On

[OUTPUT]
    Name         forward
    Match        *
    # Points directly to your upstreams definition file
    unix_path        /tmp/seastar_forward.sock
    workers        2
    Require_ack_response False
