[sources.fluent_in]
type = "fluent"
address = "0.0.0.0:24224"
#mode = "unix"
#path = "/tmp/seastar_forward.sock"

# Suppress heavy backpressure memory allocations during stress tests
#receive_buffer_bytes = 10485760 # 10MB TCP window

[sinks.drop_bench]
type = "blackhole"
inputs = ["fluent_in"]
# Emits raw throughput stats to stderr without impacting core pipeline performance
print_interval_secs = 1 

